### ISSUE TITLE
Implement NL interface

### ISSUE THREAD

**Issue by odow** [odow/NEOS.jl#17]
This would involve hooking into https://github.com/JuliaOpt/AmplNLWriter.jl. It may need some reorganisation to allow the printing but not optimizing. 

Would be nice to work this into https://github.com/odow/MPSWriter.jl, https://github.com/odow/LPWriter.jl, and https://github.com/odow/MathOptFormat.jl (and maybe even https://github.com/JuliaOpt/CoinOptServices.jl) so that we can separate out the model -> file -> NEOS -> retrieve solution steps and have it interface with MOI at the same time.

cc @jalving if you're still interested.

### Items not covered by #18 
 - [ ] split out the MPS stuff better. Use MPSWriter.jl (closes #3)
 - [ ] MathOptInterface?
 - [ ] dual solutions with NL file
 - [ ] find upstream deprecation warnings

**Comment by jalving** [comment]
Definitely still interested.  

Is this targeting any NEOS solvers in particular?  I don't believe the situation has changed since we last brought this up.  NEOS doesn't support NL files for most of the solvers.  I should bug them about this again.

**Comment by odow** [comment]
Michael Ferris is visiting us for 6 months so I'm planning on making progress while he's here and he's going to try push changes through NEOS if we need.

Ideally we tidy things up and make it easier to implement new solvers. The NL will return a .sol file so that makes parsing the solution easier.
