### ISSUE TITLE
Help wanted: update to MathOptInterface

### ISSUE THREAD

**Issue by dirkdegel** [odow/NEOS.jl#29]
I tried to install the NEOS package in Julia 1.0.4 (see code and error message below.) but the installation failed.

```
julia> using Pkg

julia> Pkg.add("NEOS")
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * NEOS (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by odow** [comment]
NEOS.jl has not been updated to Julia 1.0

**Comment by dirkdegel** [comment]
Hi Oscar,
Thanks for the information. I hope it will be updated. It is a great idea. Thanks Dirk.

**Comment by odow** [comment]
I'm going to leave this open for the next person who comes along looking.

I have no plans to update this in the near term. It would make a good project for someone looking to get into JuMP/Julia development.

**Comment by odow** [comment]
This should be pretty achievable now that MathOptInterface has support for various file-formats. 

We can start by defining an `Optimizer` like the following:
```julia
struct Optimizer <: MOI.AbstractOptimizer
    model::MOI.Utilities.Model{Float64}
    # ... some other fields for NEOS stuff
end

function MOI.optimize!(model::Optimizer)
    file = MOI.FileFormats.MPS.Model()
    MOI.copy_to(file, model)
    io = IOBuffer()
    write(io, file)
    seekstart(io)
    s_file = read(io, String)
    # send `s_file` to NEOS using current implementation
    return
end
```
