### ISSUE TITLE
MPS writer

### ISSUE THREAD

**Issue by mlubin** [odow/NEOS.jl#3]
I see that you've implemented an MPS writer here. Let us know if there's any way we can make the JuMP MPS writer more accessible or flexible, no need to duplicate work.
CC @IainNZ

**Comment by odow** [comment]
I was thinking that it would be good to have a MPB level writer package at some point for MPS, LP, NL and OSIL files all together (or in different packages).

Then you could have this package go JuMP>MPS>NEOS or JuMP>OSIL>NEOS etc

**Comment by mlubin** [comment]
CC @tkelman @JackDunnNZ

**Comment by IainNZ** [comment]
MPS writer package is fine by me, especially now package precompilation is done

**Comment by tkelman** [comment]
ref https://github.com/JuliaOpt/MathProgBase.jl/issues/54, I don't think `writeproblem` is defined in a useful way for nonlinear. So writing osil or nl without immediately solving would be a little awkward at the moment.

**Comment by mlubin** [comment]
What needs to change about `writeproblem`? You can call it after `loadnonlinearproblem!`, in which case the MPB model has all the information needed. The issue with not having an API for reading a nonlinear problem is separate.

**Comment by tkelman** [comment]
Last time I looked into this it wasn't straightforward to get at the NLPEvaluator for a function that is not operating as a solver.

**Comment by mlubin** [comment]
You can now call `buildInternalModel` on a nonlinear JuMP model and it will call `loadnonlinearproblem!` without solving.
