### ISSUE TITLE
Gurobi No Longer Supported Over XML

### ISSUE THREAD

**Issue by JZL** [odow/NEOS.jl#38]
Hi,

It's not that obvious on the NEOS website but if you use the Gurobi solver, it fails. Apparently it was never supposed to be supported over XML. I found it by intercepting all the POST responses, but you can also see it here

https://solverstudio.org/help-comments/

> The Gurobi license for NEOS does not permit connections via XML-RPC. If you look at a solver page for Gurobi, for example, https://neos-server.org/neos/solvers/milp:Gurobi/AMPL.html, you will see that the XML-RPC interface is disabled. The license only allows submissions via the web interface. If you were able to submit jobs via XML-RPC previously, that was a mistake on our part introduced during an update to the NEOS codebase. [/quote]

**Comment by odow** [comment]
Thanks. I'll update the README: https://github.com/odow/NEOSServer.jl/pull/39. I knew that the limitation used to be the case (in 2012 spent the summer working on SolverStudio and it's NEOS support...), but it worked when I wrote this package so I assumed the limitation had changed.

**Comment by JZL** [comment]
Cool thanks. This has been a very useful package, it's amazing how some problems finish to optimality with one solver in 30 seconds, and others take 8+ hours
