### ISSUE TITLE
MPS writer prints FR and MI bounds

### ISSUE THREAD

**Issue by odow** [odow/NEOS.jl#9]
User reports CPLEX model fails to solve.
https://groups.google.com/forum/#!topic/julia-opt/oKjrETIzjTs

number: 4785479
pwd:            WEVgkNvR

Likely culprit is MPS write error.

**Comment by ghost** [comment]
Thanks for looking into this, Oscar.  Here's the mps file generated as you suggested.

[neos-server-mps.txt](https://github.com/odow/NEOS.jl/files/382380/neos-server-mps.txt)

Beannachtaí,
Patrick Healy

**Comment by odow** [comment]
@healy-pa thanks for the catch. I'd actually fixed this in a new iteration of the MPS writer (take a look at the open pull request) that I haven't got around to merging

**Comment by ghost** [comment]
Thanks you, Oscar.  That did the trick and I was able to submit a job.

However, when I submitted a larger job I got:
ERROR: LoadError: XML-RPC failed
 in _send at /home/me/.julia/v0.4/NEOS/src/NEOSServer.jl:46
 in _method at /home/me/.julia/v0.4/NEOS/src/NEOSServer.jl:36
 in optimize! at /home/me/.julia/v0.4/NEOS/src/NEOSSolverInterface.jl:116
 in solve at /home/me/.julia/v0.4/JuMP/src/solvers.jl:138

The return email told me that teh output was too large:

Job results too long for email.  Download results from
https://neos-server.org/neos/admin.html
Job Number=4791864, Password=PdmVqbQA

I wonder if there's a way of splicing the output found above back into
NEOSServer.jl...

**Comment by ghost** [comment]
After submitting another job it appears that "the pipe" breaks before --
can be long before -- the job ends.  The informational email shows up later.
